spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gaebokchi?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 0248

  jpa:
    hibernate:
      ddl-auto: create #when to execute application drop table and recreate it
    properties:
      hibernate:
        #        show_sql: true   #write hibernate implementation SQL at System.out
        format_sql: true
  profiles:
    include: oauth

logging.level:
  org.hibernate.SQL: debug #write hibernate implementation SQL through logger



